name: Multiple Jobs Demo

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Building Application"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Testing Application"